apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: workload-platform-config
  namespace: argocd

spec:
  generators:
    - matrix:
        generators:
          - clusters:
              selector:
                matchLabels:
                  cluster-type: workload

          - list:
              elements:
                - component: webapp
                  namespace: webapp

  template:
    metadata:
      name: '{{nameNormalized}}-{{component}}'
      annotations:
        argocd.argoproj.io/sync-wave: "2"

    spec:
      project: default

      source:
        repoURL: https://github.com/Shashankcj/fullstact_project_gitops
        targetRevision: main

      destination:
        server: '{{server}}'
        namespace: '{{namespace}}'

      syncPolicy:
        automated:
          prune: true
          selfHeal: true

        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true