apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: external-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"

spec:
  goTemplate: true

  generators:
    - clusters:
        selector:
          matchLabels:
            cluster-type: workload

  template:
    metadata:
      name: '{{.name}}-external-secrets'

    spec:
      project: default

      sources:
      # Source 1: External Secrets Operator
      - repoURL: https://charts.external-secrets.io
        chart: external-secrets
        targetRevision: 0.9.0
        helm:
          values: |
            serviceAccount:
              create: true
              name: external-secrets

      # Source 2: Our Helm chart
      - repoURL: https://github.com/Shashankcj/platform.git
        targetRevision: main
        path: platform/external-secrets
        helm:
          parameters:
            - name: vault.server
              value: "http://10.99.1.233:8200"
            - name: vault.authMount
              value: '{{ index .metadata.labels "vault-auth-mount" }}'
            - name: vault.role
              value: "external-secrets"

      destination:
        server: '{{.server}}'
        namespace: external-secrets

      syncPolicy:
        automated:
          prune: true
          selfHeal: true

        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true