apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: workload-platform
  namespace: argocd
spec:
  generators:
  - matrix:
      generators:
      - clusters:
          selector:
            matchLabels:
              cluster-type: workload

      - list:
          elements:
            - component: metrics-server
              repoURL: https://kubernetes-sigs.github.io/metrics-server
              chart: metrics-server
              version: 3.13.0
              namespace: kube-system
              valuesFiles: platform/metrics-server/values.yaml

            - component: metallb
              repoURL: https://metallb.github.io/metallb
              chart: metallb
              version: 0.15.2
              namespace: metallb-system
              valuesFiles: platform/metallb/values.yaml

            - component: local-path-provisioner
              repoURL: https://containeroo.github.io/helm-charts
              chart: local-path-provisioner
              version: 0.0.35
              namespace: local-path-storage
              valuesFiles: platform/local-path-storage/values.yaml

             

            - component: ingress-nginx
              repoURL: https://kubernetes.github.io/ingress-nginx
              chart: ingress-nginx
              version: 4.13.3
              namespace: ingress-nginx
              valuesFiles: platform/ingress-nginx/values.yaml

            - component: cert-manager
              repoURL: https://charts.jetstack.io
              chart: cert-manager
              version: v1.18.2
              namespace: cert-manager
              valuesFiles: platform/cert-manager/values.yaml

            - component: keda
              repoURL: https://kedacore.github.io/charts
              chart: keda
              version: 2.18.0
              namespace: keda
              valuesFiles: platform/keda/values.yaml

            - component: kube-prometheus-stack
              repoURL: https://prometheus-community.github.io/helm-charts
              chart: kube-prometheus-stack
              version: 77.11.0
              namespace: monitoring
              valuesFiles: platform/kube-prometheus-stack/values.yaml

            



  template:
    metadata:
      name: '{{nameNormalized}}-{{component}}'

    spec:
      project: default

      sources:
        - repoURL: '{{repoURL}}'
          chart: '{{chart}}'
          targetRevision: '{{version}}'
          helm:
            valueFiles:
              - $values/{{valuesFiles}}

        - repoURL: https://github.com/Shashankcj/platform.git
          targetRevision: main
          ref: values


      destination:
        server: '{{server}}'
        namespace: '{{namespace}}'

      ignoreDifferences:
      - group: apps
        kind: Deployment
        name: '{{nameNormalized}}-local-path-provisioner'
        namespace: local-path-storage
        jsonPointers:
          - /spec/template/spec/hostUsers

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true