apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: clustermesh-ca
  namespace: cert-manager
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: vault-clustermesh
    kind: ClusterSecretStore

  target:
    name: clustermesh-ca
    creationPolicy: Owner
    template:
      type: kubernetes.io/tls

  data:
    - secretKey: tls.crt
      remoteRef:
        key: clustermesh
        property: ca.crt

    - secretKey: tls.key
      remoteRef:
        key: clustermesh
        property: ca.key