apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret

metadata:
  name: clustermesh-ca
  namespace: cert-manager

spec:
  refreshInterval: 1h

  secretStoreRef:
    name: vault-clustermesh
    kind: ClusterSecretStore

  target:
    name: clustermesh-ca
    creationPolicy: Owner

  data:
    - secretKey: ca.crt
      remoteRef:
        key: clustermesh
        property: ca.crt

    - secretKey: ca.key
      remoteRef:
        key: clustermesh
        property: ca.key