apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-clustermesh
  namespace: external-secrets
spec:
  provider:
    vault:
      server: {{ .Values.vault.server | quote }}
      path: "secret"
      version: "v2"
      auth:
        kubernetes:
          mountPath: {{ .Values.vault.authMount | quote }}
          role: {{ .Values.vault.role | quote }}
          serviceAccountRef:
            name: external-secrets