grafana:
  enabled: true
  replicas: 1

  adminPassword: admin123

  service:
    type: ClusterIP

  ingress:
    enabled: true
    ingressClassName: nginx


    hosts:
      - ""

    path: /grafana

  persistence:
    enabled: true
    storageClassName: local-path
    accessModes:
      - ReadWriteOnce
    size: 10Gi

prometheus:
  service:
    type: ClusterIP

  ingress:
    enabled: true
    ingressClassName: nginx


    hosts:
      ""

    paths:
      - /prometheus

  prometheusSpec:
    replicas: 1
    retention: 15d

    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: local-path
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 30Gi

alertmanager:
  enabled: true

  service:
    type: ClusterIP

  ingress:
    enabled: true
    ingressClassName: nginx


    hosts:
      ""

    paths:
      - /alertmanager

  alertmanagerSpec:
    replicas: 1

    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: local-path
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 5Gi              