grafana:
  enabled: true
  replicas: 1

  adminPassword: admin123

  grafana.ini:
    server:
      root_url: "%(protocol)s://%(domain)s/grafana"
      serve_from_sub_path: true

  service:
    type: ClusterIP

  ingress:
    enabled: true
    ingressClassName: nginx


    hosts:
      - ""

    path: /grafana

  persistence:
    enabled: true
    storageClassName: local-path
    accessModes:
      - ReadWriteOnce
    size: 10Gi

prometheus:
  service:
    type: ClusterIP

  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - ""
    paths:
      - /prometheus

  prometheusSpec:
    externalUrl: /prometheus
    routePrefix: /
    replicas: 1
    retention: 15d

    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: local-path
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 30Gi


alertmanager:
  enabled: true

  service:
    type: ClusterIP

  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - ""
    paths:
      - /alertmanager

  alertmanagerSpec:
    externalUrl: /alertmanager
    routePrefix: /
    replicas: 1

    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: local-path
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 5Gi