ipam:
  mode: kubernetes

hubble:
  relay:
    enabled: true
  ui:
    enabled: true

clustermesh:
  useAPIServer: true

  config:
    enabled: true

  apiserver:
    service:
      type: LoadBalancer